ccflags-y = -Wno-unused-function -Wno-unused-label -Wno-unused-variable

# TODO: add rules to create a multi object module

EXTRA_CFLAGS = -Wall -g

obj-m = supermodule.o
supermodule-y = mod1.o mod2.o
